version: '3.5'
services:
  consul:
    image: consul
    command: consul agent -server -client=0.0.0.0 -dev -ui -bootstrap -config-dir=/config -log-level info
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"  
    volumes:
     - ${VOLUME_ROOT}/consul/config:/config/
     
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_LOG4J_PROP: INFO
    volumes:
      - ${VOLUME_ROOT}/zookeeper:/opt/zookeeper-3.4.9/data

  zoonavigator-web:
    image: elkozmon/zoonavigator-web:latest
    ports:
     - "8000:8000"
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
    links:
     - zoonavigator-api
    depends_on:
     - zoonavigator-api
    restart: always

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:latest
    environment: 
      SERVER_HTTP_PORT: 9000

  kafka: 
    image: wurstmeister/kafka:1.0.0
    ports: 
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 999
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_ROOT}/kafka:/kafka
      
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose:
      - "9411"
      - "16686"
    ports: 
      - "9411:9411"
      - "16686:16686" 
      
  mongodb:
    image: mongo:3
    volumes:
      - ${VOLUME_ROOT}/mongodb:/data/db
      
  mosquitto:
    image: eclipse-mosquitto:1.4.12
    ports:
      - "1883:1883"
          
networks: 
    default: 
        driver: overlay
        name: sitewhere
